import streamlit as st
from database.standard_index import  init_standard_index_db

def display_standard_detail(standard_code:str):
    standard_index=init_standard_index_db()
    detail=standard_index.detail(standard_code)
    st.markdown("##### 基本信息\n\n---")
    st.markdown("**标准英文名称：**")
    st.write(detail['english_name'])
    st.markdown("---")
    col1,col2=st.columns(2)
    with col1:
        col1.markdown("**标准分类：**")
        col1.write(detail['standard_type'])
        col1.markdown("---")
        col1.markdown("**专业：**")
        col1.write(detail['specialty'])
        col1.markdown("---")           
        col1.markdown("**ICS分类号：**")
        col1.write(detail['ics_classification'])
        col1.markdown("---")
        col1.markdown("**发布日期：**")
        col1.write(detail['release_date'])
        col1.markdown("---")
        
    with col2:
        col2.markdown("**标准状态：**")
        col2.write(detail['status'])
        col2.markdown("---")           
        col2.markdown("**标准性质：**")
        col2.write(detail['standard_nature'])     
        col2.markdown("---")           
        col2.markdown("**CCS分类号：**")
        col2.write(detail['ccs_classification'])
        col2.markdown("---")
        col2.markdown("**实施日期：**")
        col2.write(detail['implementation_date'])
        col2.markdown("---")
    st.markdown("##### 起草单位及其他")
    st.markdown("**起草单位：**")
    st.write(detail['drafting_unit'])
    st.markdown("---")
    st.markdown("**技术委员会（或技术归口单位）：**")
    st.write(detail['responsible_unit'])
    st.markdown("---")